name: NodeJS with Webpack

on:
  push:
    branches: ['master', 'develop']
  pull_request:
    branches: ['master', 'develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup current workflow
        id: setup-workflow
        run: |
          BRANCH=${GITHUB_REF##*/}
          echo "CURRENT_BRANCH=${BRANCH}" >> "$GITHUB_OUTPUT"
          PACKAGE_VERSION=$(node -e "console.log(require('./package.json').version)")
          HASH=${GITHUB_SHA::6}
          VERSION=$PACKAGE_VERSION-$(date '+%Y%m%d-%H%M%S')-$HASH
          echo "VERSION=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Cache npm dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
          key: ${{ hashFiles('package-lock.json') }}

      - name: Update development version
        if: ${{ steps.setup-workflow.outputs.CURRENT_BRANCH != 'master' }}
        run: |
          npm version ${{ steps.setup-workflow.outputs.VERSION }} --no-git-tag-version

      - name: Install requirements
        if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: |
          npm ci

      - name: Linting
        run: |
          npm run lint --if-present

      - name: Test
        run: |
          npm run test --if-present

      - name: Build
        run: |
          npm run build --if-present
