name: RELEASE

on: [workflow_dispatch]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache npm dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
          key: ${{ hashFiles('package-lock.json') }}

      - name: Install deps
        if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: npm ci

      - name: Linting
        run: |
          npm run lint --if-present

      # - name: Test
      #   run: |
      #     npm run test --if-present
      - name: Test variables
        run: |
          if [ -n "$GITHUB_TOKEN" ]; then
            echo "Github token ok "
          else
            echo "Github Token NOT ok"
          fi
          
          if [ -n "$NPM_TOKEN" ]; then
            echo "Npm token ok"
          else
            echo "Npm token NOT ok"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_PERMISSION }}          
          NPM_TOKEN: ${{ secrets.PUBLISH_TOKEN }}

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_PERMISSION }}
          NPM_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
